name: OpenMath
version: 11.4.2
date: 2017-02-28
description: |
    OpenMath functionality in GAP

authors:
    - name: Marco Costantini
    - name: Alexander Konovalov
      url: http://blogs.cs.st-andrews.ac.uk/alexk/
    - name: Max Nicosia
      url: http://www-edc.eng.cam.ac.uk/~lmn27/
    - name: Andrew Solomon

maintainers:
    - name: Alexander Konovalov
      url: http://blogs.cs.st-andrews.ac.uk/alexk/
    - name: Max Nicosia
      url: http://www-edc.eng.cam.ac.uk/~lmn27/

GAP: ">=4.8"

needed-pkgs:
    - name: "GapDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.4"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/openmath
readme: README.md
packageinfo: https://gap-packages.github.io/openmath/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/openmath/releases/download/v11.4.2/OpenMath-11.4.2.tar.gz

abstract: |
    This package provides an <a href="http://www.openmath.org/">OpenMath</a> phrasebook for <span class="pkgname">GAP</span>. This package allows <span class="pkgname">GAP</span> users to import and export mathematical objects encoded in OpenMath, for the purpose of exchanging them with other applications that are OpenMath enabled.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
