name: OpenMath
version: "11.5.3"
license: "GPL-2.0-or-later"
date: 2023-02-25
description: |
    OpenMath functionality in GAP

authors:
    - name: Marco Costantini
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Max Nicosia
      url: http://www-edc.eng.cam.ac.uk/~lmn27/
    - name: Andrew Solomon

maintainers:
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Max Nicosia
      url: http://www-edc.eng.cam.ac.uk/~lmn27/

GAP: " >= 4.9.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.5.1"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/openmath
readme: README.md
packageinfo: https://gap-packages.github.io/openmath/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/openmath/releases/download/v11.5.3/OpenMath-11.5.3.tar.gz

abstract: |
    This package provides an <a href="http://www.openmath.org/">OpenMath</a> phrasebook for <span class="pkgname">GAP</span>. This package allows <span class="pkgname">GAP</span> users to import and export mathematical objects encoded in OpenMath, for the purpose of exchanging them with other applications that are OpenMath enabled.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    OpenMath, Phrasebook.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CKNS23</span>]   <b class='BibAuthor'>Costantini, M., Konovalov, O., Nicosia, M. and Solomon, A.</b>,
     <i class='BibTitle'>OpenMath, OpenMath functionality in GAP,
             Version 11.5.3</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/openmath">https://gap-packages.github.io/openmath</a></span>.
    </p>
    

bibtex: |
    @misc{ OpenMath11.5.3,
      author =           {Costantini,  M.  and Konovalov, O. and Nicosia, M. and
                          Solomon, A.},
      title =            {{OpenMath},  OpenMath  functionality in GAP, {V}ersion
                          11.5.3},
      month =            {Feb},
      year =             {2023},
      note =             {Refereed GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/openmath}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{openmath}}},
      keywords =         {OpenMath; Phrasebook},
      printedkey =       {CKNS23}
    }

